=== lazavini/PRI2018/TP4/manifesto.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT manifesto (meta, equipa, resumo, resultados) >

<!ELEMENT meta (id, título, subtítulo?, dinício?, dfim, supervisor) >
<!ELEMENT id (#PCDATA) >
<!ELEMENT título (#PCDATA) >
<!ELEMENT subtítulo (#PCDATA) >
<!ELEMENT dinício (#PCDATA) >
<!ELEMENT dfim (#PCDATA) >

<!ELEMENT supervisor (nome, email, website?) >
<!ELEMENT nome (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT website (#PCDATA) >

<!ELEMENT equipa (elemento+) >
<!ELEMENT elemento (id, nome, email, website?, foto?) >
<!ELEMENT foto EMPTY >
<!ATTLIST foto
          path CDATA #REQUIRED >
          
<!ELEMENT resumo (para+) >
<!ELEMENT para (#PCDATA | b | i)* >
<!ELEMENT b (#PCDATA | i)* >
<!ELEMENT i (#PCDATA | b)* >

<!ELEMENT resultados (resultado+) >
<!ELEMENT resultado (#PCDATA) >
<!ATTLIST resultado
          path CDATA #IMPLIED >

=== lazavini/PRI2018/TP5/manifesto_tp5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE manifesto SYSTEM "file:/home/lazaro/Documentos/Uminho/Disciplinas/PRI/TP4/manifesto.dtd">
<manifesto>
    <meta>
        <id>PRI2018::TP4</id>
        <título>Arquivo de Músicas Digitais JSON</título>
        <subtítulo>TP5 da cadeira de PRI doutoramento 2018/2019</subtítulo>
        <dinício>15 de Outubro de 2018</dinício>
        <dfim>22 de Outubro de 2018</dfim>
        <supervisor>
            <nome>Dr.José Carlos Ramalho</nome>
            <email>jcr@di.uminho.pt</email>
            <website>http://www.di.uminho.pt/~jcr</website>
        </supervisor>
    </meta>
    <equipa>
        <elemento>
            <id>ID8120</id>
            <nome>Lázaro Vinícius de Oliveira Lima</nome>
            <email>lazaro.lima@ifb.edu.br</email>
        </elemento>
    </equipa>
    <resumo>
        <para>Neste trabalho prático foi proposto a organização e estruturação do Arquivo de Mísicas Digitais.</para>
        <para>Através de um stylesheet previamente feito, foram geradas instruções HTML capazes de dar resposta ao desafio proposto. Todo as informações das músicas estão representado em XML, foi necessário o varrimento deste para captar as informações pretendidas.</para>
        <para>Na página principal contem index.pug, cuja função é a de apresentar as informações das musicas e de direcionar o utilizador.</para>
    </resumo>
    <resultados>
        <resultado path="https://github.com/lazavini/PRI2018/blob/master/TP5/website/index.html">Página principal das Músicas</resultado>
        <resultado path="https://github.com/lazavini/PRI2018/blob/master/TP5/arquivo-musica-digital2html.xsl">Stylesheet usado no ficheiro XML (XSL)</resultado>
        <resultado path="https://github.com/lazavini/PRI2018/blob/master/TP5/arquivo-musica-digital.xml">Representação das Informações das Músicas em XML</resultado>
        <resultado path="https://github.com/lazavini/PRI2018/blob/master/TP5/servidor.js"> Servidor </resultado>
    </resultados>
</manifesto>
